/// <reference types="bun-types" />
import { $ } from 'bun';
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const targets = [
  { target: 'bun-windows-x64', outfile: 'binaries/camunda-demo-hub-windows.exe' },
  { target: 'bun-linux-x64',   outfile: 'binaries/camunda-demo-hub-linux-x64'   },
  { target: 'bun-darwin-arm64', outfile: 'binaries/camunda-demo-hub-mac-arm64'  },
  { target: 'bun-darwin-x64',  outfile: 'binaries/camunda-demo-hub-mac-x64'     },
];

await mkdir('binaries', { recursive: true });

console.log('Building frontend...');
await $`npx vite build`;

console.log('\nGenerating asset manifest...');
async function walk(dir: string, base = dir): Promise<string[]> {
  const entries = await readdir(dir);
  const out: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry);
    const s = await stat(full);
    if (s.isDirectory()) out.push(...await walk(full, base));
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

const files = await walk('dist');
const imports = files.map((f, i) => `import f${i} from '../dist/${f}' with { type: 'file' };`).join('\n');
const entries = files.map((f, i) => `  '/${f}': f${i},`).join('\n');
const manifest = `// AUTO-GENERATED by scripts/build-binaries.ts — do not edit
${imports}

export const ASSETS: Record<string, string> = {
${entries}
};
`;
await writeFile('src/dist-manifest.ts', manifest);
console.log(`  ${files.length} assets indexed`);

console.log('\nCompiling binaries...');
for (const { target, outfile } of targets) {
  process.stdout.write(`  ${target} → ${outfile} ... `);
  await $`bun build --compile --target=${target} standalone.ts --outfile ${outfile}`.quiet();
  console.log('done');
}

console.log('\nAll binaries written to ./binaries/');
console.log('\nDistribute each binary alongside a .env file containing:');
console.log('  CAMUNDA_BASE_URL=...');
console.log('  CAMUNDA_OAUTH_URL=...');
console.log('  CAMUNDA_CLIENT_ID=...');
console.log('  CAMUNDA_CLIENT_SECRET=...');
