// AUTO-GENERATED by scripts/build-binaries.ts — do not edit
import f0 from '../dist/assets/index-BYst3TDE.js' with { type: 'file' };
import f1 from '../dist/assets/index-EkA5ywho.css' with { type: 'file' };
import f2 from '../dist/favicon.svg' with { type: 'file' };
import f3 from '../dist/icons.svg' with { type: 'file' };
import f4 from '../dist/index.html' with { type: 'file' };
import f5 from '../dist/logos/allied-henna-federation.svg' with { type: 'file' };
import f6 from '../dist/logos/allied-henna-insurance.svg' with { type: 'file' };
import f7 from '../dist/logos/allied-henna-telecom.svg' with { type: 'file' };
import f8 from '../dist/logos/allied-henna.svg' with { type: 'file' };

export const ASSETS: Record<string, string> = {
  '/assets/index-BYst3TDE.js': f0,
  '/assets/index-EkA5ywho.css': f1,
  '/favicon.svg': f2,
  '/icons.svg': f3,
  '/index.html': f4,
  '/logos/allied-henna-federation.svg': f5,
  '/logos/allied-henna-insurance.svg': f6,
  '/logos/allied-henna-telecom.svg': f7,
  '/logos/allied-henna.svg': f8,
};
